"""empty message

Revision ID: bb1f2a31c2c7
Revises: 
Create Date: 2026-01-29 23:19:02.293814

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bb1f2a31c2c7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tokens',
    sa.Column('id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True)
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.Column('salt', postgresql.BYTEA(), nullable=True),
    sa.Column('first_name', sa.String(length=32), nullable=True),
    sa.Column('second_name', sa.String(length=40), nullable=True),
    sa.Column('gender', sa.Enum('male', 'female', name='gender'), nullable=True),
    sa.Column('birthday', sa.Date(), nullable=True),
    sa.Column('biography', sa.String(length=500), nullable=True),
    sa.Column('city', sa.String(length=250), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('tokens')
    # ### end Alembic commands ###
