import re

MIN_PASSWORD_LENGTH = 10
MAX_PASSWORD_LENGTH = 25

MIN_FIRST_NAME_LENGTH = 2
MAX_FIRST_NAME_LENGTH = 32


MIN_SECOND_NAME_LENGTH = 2
MAX_SECOND_NAME_LENGTH = 40


MIN_CITY_LENGTH = 2
MAX_CITY_LENGTH = 250

MIN_BIOGRAPHY_LENGTH = 0
MAX_BIOGRAPHY_LENGTH = 500

LOWERCASE_PATTERN = "(?=.*[a-z])"
UPPERCASE_PATTERN = "(?=.*[A-Z])"
DIGITAL_PATTERN = "(?=.*[0-9])"
SPECIAL_PATTERN = "(?=.*[!@#$%^&*()_+\-=\[\]{{}};':\"\\|,.<>\/?])"
PASSWORD_STRENGTH_REGULAR = (
    rf"^{LOWERCASE_PATTERN}{UPPERCASE_PATTERN}{SPECIAL_PATTERN}{DIGITAL_PATTERN}"
)
PASSWORD_STRENGTH_REGEX = re.compile(PASSWORD_STRENGTH_REGULAR)
